#define PLOOPY_DPI_OPTIONS { 400, 600, 1200, 1600 }
#define PLOOPY_DPI_DEFAULT 3

#define MOUSE_EXTENDED_REPORT
#define WHEEL_EXTENDED_REPORT
// #define POINTING_DEVICE_HIRES_SCROLL_ENABLE
// #define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 120
// #define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 1

#define MK_3_SPEED

#define PLOOPY_DRAGSCROLL_DIVISOR_H 16.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 16.0
